// ─── INDstocks authentication ─────────────────────────────────────────────────
// Kite needed an interactive browser login every single morning, and the whole
// "session expired, log in now" failure class in the old app came from that.
// INDstocks issues a 24h token from a TOTP secret, so this process can mint its
// own token with no human in the loop.
//
// Rules from the API docs that this file encodes:
//   - POST /generate/token with header `x-api-key: <client id>` and body
//     { mpin, totp }; the response field is `token`, NOT `access_token`.
//   - Only ONE TOTP token is valid at a time — minting a new one kills the old.
//   - Minimum 60 seconds between generations (rate limited).
//   - 5 wrong TOTP codes triggers a 15-minute lockout, so we never retry a
//     rejected code blindly.
//
// INDstocks also supports a SECOND path: a token generated by hand in the
// dashboard and pasted in as IND_ACCESS_TOKEN. That works immediately with no
// TOTP setup, but it cannot be refreshed by this process — when it expires,
// trading stops until a human pastes a new one. TOTP is therefore preferred
// whenever both are configured, and the app warns when running on a static token.

import { generateSync } from "otplib";

const BASE = process.env.IND_API_BASE || "https://api.indstocks.com";

const CLIENT_ID = process.env.IND_CLIENT_ID || "";
const MPIN      = process.env.IND_MPIN      || "";

/** A TOTP secret is Base32: A-Z and 2-7 only. Anything else is not a secret —
 *  usually an API key pasted into the wrong field.
 *
 *  This is validated rather than trusted because an unusable secret used to
 *  brick the whole app: a non-empty value made canMint() report true, which
 *  disabled the working access-token fallback, and then generateSync() threw on
 *  every single call. An optional credential being malformed must degrade to
 *  "no auto-refresh", never to "nothing works". */
function isBase32Secret(v: string): boolean {
  return /^[A-Z2-7]+=*$/.test(v.replace(/\s+/g, "").toUpperCase());
}

const TOTP_SECRET_RAW = (process.env.IND_TOTP_SECRET || "").replace(/\s+/g, "");
const TOTP_SECRET     = isBase32Secret(TOTP_SECRET_RAW) ? TOTP_SECRET_RAW.toUpperCase() : "";

if (TOTP_SECRET_RAW && !TOTP_SECRET) {
  console.warn(
    "[Auth] IND_TOTP_SECRET is not a valid Base32 TOTP secret (only A-Z and 2-7 are " +
    "allowed) — ignoring it. Automatic token refresh is OFF. If you pasted your " +
    "Client ID or API key there, move it to IND_CLIENT_ID; the real secret comes " +
    "from the dashboard's TOTP QR code.",
  );
}
/** Manually pasted dashboard token — the fallback when TOTP isn't set up. */
const STATIC_TOKEN = process.env.IND_ACCESS_TOKEN || "";

/** Tokens last 24h; refresh early so a long-running session never trades on an
 *  expiring token. */
const TOKEN_TTL_MS     = 24 * 60 * 60 * 1000;
const REFRESH_BEFORE_MS = 60 * 60 * 1000; // refresh 1h before expiry
const MIN_MINT_GAP_MS   = 65 * 1000;      // API allows 1/min; leave headroom

type TokenState = { token: string; mintedAt: number };

/**
 * ALL auth state is anchored on globalThis, never module scope.
 *
 * The login route runs in Next's route module graph; the price feed and
 * schedulers run in the instrumentation graph. Those are separate copies of
 * this module. With module-level state, logging in would give the ROUTE a
 * token while the RUNTIME stayed unauthenticated — the UI would look signed in
 * and serve chain data, while the WebSocket quietly failed to connect and no
 * live price ever arrived. Anchoring here keeps exactly one token.
 */
type AuthState = {
  token: TokenState | null;
  /** Credentials entered at runtime via the login screen; they take precedence
   *  over .env so re-authenticating needs no filesystem edit or restart. */
  runtimeClientId: string | null;
  runtimeMpin: string | null;
  lastMintAt: number;
  /** Set after a lockout-triggering failure so we stop hammering a locked account. */
  lockedUntil: number;
};

function auth(): AuthState {
  const g = globalThis as any;
  g.__INDMONEY_AUTH__ ??= {
    token: null,
    runtimeClientId: null,
    runtimeMpin: null,
    lastMintAt: 0,
    lockedUntil: 0,
  } satisfies AuthState;
  return g.__INDMONEY_AUTH__ as AuthState;
}

// In-flight mint is per-graph; that is fine, the guard only prevents a double
// mint from concurrent callers in the same process tick.
let mintingPromise: Promise<string> | null = null;

function clientId(): string { return auth().runtimeClientId ?? CLIENT_ID; }
function mpin():     string { return auth().runtimeMpin     ?? MPIN; }

/** TOTP minting needs all three; a static token needs none of them. */
export function canMint(): boolean {
  return clientId().length > 0 && mpin().length > 0 && TOTP_SECRET.length > 0;
}

/** True when the login screen can offer the TOTP form (client id known,
 *  no stored secret — the user types the 6-digit code themselves). */
export function hasClientId(): boolean {
  return clientId().length > 0;
}

export function isConfigured(): boolean {
  return canMint() || STATIC_TOKEN.length > 0;
}

/** True when this process can replace its own token without a human. */
export function canAutoRefresh(): boolean {
  return canMint();
}

export function hasToken(): boolean {
  const t = auth().token;
  if (t && Date.now() - t.mintedAt < TOKEN_TTL_MS) return true;
  return !!STATIC_TOKEN && !canMint();
}

/** Adopt a token the user pasted in the login screen. */
export function setAccessToken(token: string) {
  auth().token = { token: token.trim(), mintedAt: Date.now() };
  console.log("[Auth] Access token set from login screen");
}

export function clearAccessToken() {
  const a = auth();
  a.token = null;
  a.runtimeClientId = null;
  a.runtimeMpin = null;
  console.log("[Auth] Access token cleared (logged out)");
}

/**
 * Mint a token from a 6-digit code the user just read off their authenticator.
 * This is the login-screen path; it does NOT need IND_TOTP_SECRET, because the
 * human supplies the code.
 *
 * INDstocks locks the account for 15 minutes after 5 bad codes, so a rejected
 * code is surfaced to the user immediately and never retried automatically.
 */
export async function loginWithTotp(opts: { clientId?: string; mpin: string; totp: string }) {
  const id = (opts.clientId ?? clientId()).trim();
  if (!id) throw new Error("Client ID is required");
  if (Date.now() < auth().lockedUntil) {
    const mins = Math.ceil((auth().lockedUntil - Date.now()) / 60000);
    throw new Error(`Locked out for another ~${mins} min after too many wrong codes`);
  }

  const res = await fetch(`${BASE}/generate/token`, {
    method: "POST",
    headers: { "x-api-key": id, "Content-Type": "application/json" },
    body: JSON.stringify({ mpin: opts.mpin, totp: opts.totp }),
  });
  const body = await res.json().catch(() => ({} as any));

  if (!res.ok) {
    const msg = body?.message || body?.error || `HTTP ${res.status}`;
    throw new Error(String(msg));
  }

  const token: string = body?.token || body?.data?.token || body?.access_token || "";
  if (!token) throw new Error("INDstocks returned no token");

  const a = auth();
  a.runtimeClientId = id;
  a.runtimeMpin     = opts.mpin;
  a.token           = { token, mintedAt: Date.now() };
  a.lastMintAt      = Date.now();
  console.log("[Auth] Logged in via TOTP");
  return token;
}

function needsRefresh(): boolean {
  const t = auth().token;
  if (!t) return true;
  return Date.now() - t.mintedAt > TOKEN_TTL_MS - REFRESH_BEFORE_MS;
}

/** Current token, minting or refreshing if needed. Concurrent callers share one
 *  in-flight mint — important because minting twice invalidates the first token. */
export async function getAccessToken(): Promise<string> {
  const a = auth();
  // A token set by the login screen always wins — it is the freshest proof of
  // identity we have, and it is what the runtime must use too.
  if (a.token && !needsRefresh()) return a.token.token;

  // A pasted .env token is the fallback when TOTP isn't available.
  if (!canMint() && STATIC_TOKEN) return STATIC_TOKEN;
  if (mintingPromise) return mintingPromise;

  mintingPromise = mint()
    .finally(() => { mintingPromise = null; });
  return mintingPromise;
}

/** Force a new token — called when a request comes back 401. */
export async function refreshAccessToken(): Promise<string> {
  auth().token = null;
  if (!canMint() && STATIC_TOKEN) {
    // Nothing this process can do — say so loudly rather than silently
    // retrying a dead token all day.
    throw new Error(
      "INDstocks token expired and there is no TOTP secret to mint a new one. " +
      "Paste a fresh token into IND_ACCESS_TOKEN, or set IND_CLIENT_ID + IND_MPIN + " +
      "IND_TOTP_SECRET so the app can refresh itself.",
    );
  }
  return getAccessToken();
}

async function mint(): Promise<string> {
  if (!canMint()) {
    throw new Error(
      "INDstocks credentials missing — set IND_CLIENT_ID, IND_MPIN and IND_TOTP_SECRET " +
      "(or IND_ACCESS_TOKEN for a manually pasted dashboard token)",
    );
  }
  if (Date.now() < auth().lockedUntil) {
    const mins = Math.ceil((auth().lockedUntil - Date.now()) / 60000);
    throw new Error(`INDstocks TOTP locked out for another ~${mins} min — not retrying`);
  }

  // Respect the 1-per-minute mint limit rather than getting a 429 for it.
  const since = Date.now() - auth().lastMintAt;
  if (since < MIN_MINT_GAP_MS) {
    await sleep(MIN_MINT_GAP_MS - since);
  }

  // otplib v13 defaults are Google-Authenticator compatible (TOTP, SHA-1,
  // 6 digits, 30s step) — the same scheme INDstocks' dashboard QR uses.
  const totp = generateSync({ secret: TOTP_SECRET, strategy: "totp" });
  auth().lastMintAt = Date.now();

  const res = await fetch(`${BASE}/generate/token`, {
    method: "POST",
    headers: { "x-api-key": clientId(), "Content-Type": "application/json" },
    body: JSON.stringify({ mpin: mpin(), totp }),
  });

  const body = await res.json().catch(() => ({} as any));

  if (!res.ok) {
    const msg = body?.message || body?.error || `HTTP ${res.status}`;
    // A wrong-code response is the one failure we must NOT retry into a lockout.
    if (/totp|invalid|incorrect/i.test(String(msg))) {
      auth().lockedUntil = Date.now() + 15 * 60 * 1000;
      throw new Error(
        `INDstocks rejected the TOTP (${msg}). Check IND_TOTP_SECRET and the server clock; ` +
        `pausing token generation for 15 min to avoid an account lockout.`,
      );
    }
    throw new Error(`INDstocks token generation failed: ${msg}`);
  }

  // Docs are explicit that the field is `token`, but accept the common
  // alternatives rather than failing on a wire-format change.
  const token: string = body?.token || body?.data?.token || body?.access_token || "";
  if (!token) {
    throw new Error(`INDstocks token response had no token field: ${JSON.stringify(body).slice(0, 200)}`);
  }

  auth().token = { token, mintedAt: Date.now() };
  console.log(`[Auth] INDstocks token minted, valid ~24h (expires ${new Date(Date.now() + TOKEN_TTL_MS).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST)`);
  return token;
}

function sleep(ms: number) { return new Promise((r) => setTimeout(r, ms)); }

export function tokenAge(): number | null {
  const t = auth().token;
  return t ? Date.now() - t.mintedAt : null;
}
